config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :discounts
  resources :fittings
  resources :dosifications
  resources :orders
  resources :combos
  resources :branches
  resources :products
  resources :categories
  root 'main#index'

  # Products
  get '/products/:id/branches' => 'products#branches'
  get '/products/:id/branches/new' => 'products#add_branch'
  post '/products/:id/branches/create' => 'products#add_product_branch'
  get '/update_branch_cost/:id' => 'products#update_branch_cost'
  post '/update_branch_cost_form/:id' => 'products#update_branch_cost_form'

  # Combos
  get '/combos/:id/products' => 'combos#products'
  get '/combos/:id/products/new' => 'combos#add_product'
  post '/combos/:id/products/create' => 'combos#add_product_combo'

  # Orders
  get '/orders/:id/products' => 'orders#products'
  get '/orders/:id/add_product' => 'orders#add_product'
  get '/orders/:id/add_combo' => 'orders#add_combo'
  post '/orders/:id/products/create_product' => 'orders#add_product_order'
  post '/orders/:id/products/create_combo' => 'orders#add_combo_order'
  get '/orders/:id/close' => 'orders#close'
  get '/orders/:id/print' => 'orders#print'
  get '/orders/:id/partial_print' => 'orders#partial_print'
  get '/order_details/:id' => 'orders#order_details'
  get '/order_now' => 'orders#order_now'
  get '/close_shift' => 'orders#close_shift'
  get '/remove_item/:id' => 'orders#remove_item'
  get '/disable_order/:id' => 'orders#disable_order'
  get '/enable_order/:id' => 'orders#enable_order'

  # Reports
  get '/reports' => 'reports#index'
  get '/orders_report' => 'reports#orders_report'
  get '/products_report' => 'reports#products_report'
  get '/orders_report_excel' => 'reports#orders_report_excel'
  get '/products_report_excel' => 'reports#products_report_excel'
  get '/accounting_report' => 'reports#accounting_report'
  get '/accounting_report_disabled' => 'reports#accounting_report_disabled'
  get '/accounting_txt' => 'reports#accounting_txt'
  get '/accounting_disabled_txt' => 'reports#accounting_disabled_txt'

  # Admin
  get '/users' => 'admin#users'
  get '/new_user' => 'admin#new_user'
  post '/create_user' => 'admin#create_user'
  get '/add_branch_to_user/:id' => 'admin#add_branch_to_user'
  post '/add_branch_to_user_post/:id' => 'admin#add_branch_to_user_post'

  get '/code_control_test' => 'dosifications#code_control_test'
  get '/test_code_control' => 'dosifications#test_code_control'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/branch.rb
class Branch < ApplicationRecord
	has_many :branch_products
	has_many :combos
	has_many :orders
	has_many :dosifications
	has_many :users
	has_many :user_branches

	def products_in_branch
		products = []
		self.branch_products.each do |p|
			products.push(p.product)
		end
		products
	end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: [:show, :edit, :update, :destroy]

  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to branches_url, notice: 'Correctamente creado' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to branches_url, notice: 'Correctamente editado' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Correctamente eliminado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:name, :description, :address, :city)
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= form_with(model: branch, local: true) do |form| %>
  <% if branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
      <% branch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Nombre" %>
    <%= form.text_field :name, id: :branch_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Descripción" %>
    <%= form.text_area :description, id: :branch_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Dirección" %>
    <%= form.text_field :address, id: :branch_address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Ciudad" %>
    <%= form.text_field :city, id: :branch_city, class: "form-control" %>
  </div>

  <div class="actions">
    <center>
      <%= form.submit "Aceptar", class: "btn btn-primary" %>
      <%= link_to 'Cancelar', '/branches', class: "btn btn-danger" %>
    </center>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h1>Editar sucursal</h1>

<%= render 'form', branch: @branch %>

app/views/branches/index.html.erb
<h1>Sucursales</h1>

<div class="row">
  <div class="col-lg-3">
    <%= link_to 'Crear sucursal', new_branch_path, class: "btn btn-primary btn-block" %>    
  </div>
</div>

<table class="table table-stripped table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Dirección</th>
      <th>Ciudad</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @branches.each do |branch| %>
      <tr>
        <td><%= branch.name %></td>
        <td><%= branch.description %></td>
        <td><%= branch.address %></td>
        <td><%= branch.city %></td>
        <td><%= link_to 'Editar', edit_branch_path(branch) %></td>
        <!--<td><%= link_to 'Eliminar', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>



app/views/branches/new.html.erb
<h1>Crear sucursal</h1>

<%= render 'form', branch: @branch %>


app/views/branches/show.html.erb


<p>
  <strong>Name:</strong>
  <%= @branch.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @branch.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @branch.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @branch.city %>
</p>

<%= link_to 'Edit', edit_branch_path(@branch) %> |
<%= link_to 'Back', branches_path %>