config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :discounts
  resources :fittings
  resources :dosifications
  resources :orders
  resources :combos
  resources :branches
  resources :products
  resources :categories
  root 'main#index'

  # Products
  get '/products/:id/branches' => 'products#branches'
  get '/products/:id/branches/new' => 'products#add_branch'
  post '/products/:id/branches/create' => 'products#add_product_branch'
  get '/update_branch_cost/:id' => 'products#update_branch_cost'
  post '/update_branch_cost_form/:id' => 'products#update_branch_cost_form'

  # Combos
  get '/combos/:id/products' => 'combos#products'
  get '/combos/:id/products/new' => 'combos#add_product'
  post '/combos/:id/products/create' => 'combos#add_product_combo'

  # Orders
  get '/orders/:id/products' => 'orders#products'
  get '/orders/:id/add_product' => 'orders#add_product'
  get '/orders/:id/add_combo' => 'orders#add_combo'
  post '/orders/:id/products/create_product' => 'orders#add_product_order'
  post '/orders/:id/products/create_combo' => 'orders#add_combo_order'
  get '/orders/:id/close' => 'orders#close'
  get '/orders/:id/print' => 'orders#print'
  get '/orders/:id/partial_print' => 'orders#partial_print'
  get '/order_details/:id' => 'orders#order_details'
  get '/order_now' => 'orders#order_now'
  get '/close_shift' => 'orders#close_shift'
  get '/remove_item/:id' => 'orders#remove_item'
  get '/disable_order/:id' => 'orders#disable_order'
  get '/enable_order/:id' => 'orders#enable_order'

  # Reports
  get '/reports' => 'reports#index'
  get '/orders_report' => 'reports#orders_report'
  get '/products_report' => 'reports#products_report'
  get '/orders_report_excel' => 'reports#orders_report_excel'
  get '/products_report_excel' => 'reports#products_report_excel'
  get '/accounting_report' => 'reports#accounting_report'
  get '/accounting_report_disabled' => 'reports#accounting_report_disabled'
  get '/accounting_txt' => 'reports#accounting_txt'
  get '/accounting_disabled_txt' => 'reports#accounting_disabled_txt'

  # Admin
  get '/users' => 'admin#users'
  get '/new_user' => 'admin#new_user'
  post '/create_user' => 'admin#create_user'
  get '/add_branch_to_user/:id' => 'admin#add_branch_to_user'
  post '/add_branch_to_user_post/:id' => 'admin#add_branch_to_user_post'

  get '/code_control_test' => 'dosifications#code_control_test'
  get '/test_code_control' => 'dosifications#test_code_control'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fitting.rb
class Fitting < ApplicationRecord
	has_and_belongs_to_many :products
	has_and_belongs_to_many :combos
	has_many :order_item_fittings
end

app/controllers/fittings_controller.rb
class FittingsController < ApplicationController
  before_action :set_fitting, only: [:show, :edit, :update, :destroy]

  # GET /fittings
  # GET /fittings.json
  def index
    @fittings = Fitting.all
  end

  # GET /fittings/1
  # GET /fittings/1.json
  def show
  end

  # GET /fittings/new
  def new
    @fitting = Fitting.new
  end

  # GET /fittings/1/edit
  def edit
  end

  # POST /fittings
  # POST /fittings.json
  def create
    @fitting = Fitting.new(fitting_params)

    respond_to do |format|
      if @fitting.save
        format.html { redirect_to fittings_url, notice: 'Correctamente creado' }
        format.json { render :show, status: :created, location: @fitting }
      else
        format.html { render :new }
        format.json { render json: @fitting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fittings/1
  # PATCH/PUT /fittings/1.json
  def update
    respond_to do |format|
      if @fitting.update(fitting_params)
        format.html { redirect_to fittings_url, notice: 'Correctamente editado' }
        format.json { render :show, status: :ok, location: @fitting }
      else
        format.html { render :edit }
        format.json { render json: @fitting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fittings/1
  # DELETE /fittings/1.json
  def destroy
    @fitting.destroy
    respond_to do |format|
      format.html { redirect_to fittings_url, notice: 'Correctamente eliminado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fitting
      @fitting = Fitting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fitting_params
      params.require(:fitting).permit(:name, :description, :cost)
    end
end

app/helpers/fittings_helper.rb
module FittingsHelper
end

app/views/fittings/_form.html.erb
<%= form_with(model: fitting, local: true) do |form| %>
  <% if fitting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fitting.errors.count, "error") %> prohibited this fitting from being saved:</h2>

      <ul>
      <% fitting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Nombre" %>
    <%= form.text_field :name, id: :fitting_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Descripción" %>
    <%= form.text_area :description, id: :fitting_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Costo" %>
    <%= form.text_field :cost, id: :fitting_cost, class: "form-control" %>
  </div>

  <div class="actions">
    <center>
      <%= form.submit "Aceptar", class: "btn btn-primary" %>
      <%= link_to 'Cancelar', '/fittings', class: "btn btn-danger" %>
    </center>
  </div>
<% end %>

app/views/fittings/edit.html.erb
<h1>Editar Guarnición</h1>

<%= render 'form', fitting: @fitting %>


app/views/fittings/index.html.erb


<h1>Guarniciones</h1>

<div class="row">
  <div class="col-lg-3">
    <%= link_to 'Crear guarnición', new_fitting_path, class: "btn btn-primary btn-block" %>
  </div>
</div>

<table class="table table-stripped table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Costo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fittings.each do |fitting| %>
      <tr>
        <td><%= fitting.name %></td>
        <td><%= fitting.description %></td>
        <td><%= fitting.cost %></td>
        <td><%= link_to 'Editar', edit_fitting_path(fitting) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



app/views/fittings/new.html.erb
<h1>Crear Guarnición</h1>

<%= render 'form', fitting: @fitting %>


app/views/fittings/show.html.erb


<p>
  <strong>Name:</strong>
  <%= @fitting.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fitting.description %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @fitting.cost %>
</p>

<%= link_to 'Edit', edit_fitting_path(@fitting) %> |
<%= link_to 'Back', fittings_path %>